# ==========================================================================
# CRE WORKFLOW SETTINGS FILE
# ==========================================================================
# Workflow-specific settings for CRE CLI targets.
# Each target defines user-workflow and workflow-artifacts groups.
# Settings here override CRE Project Settings File values.
#
# Example custom target:
# my-target:
#   user-workflow:
#     workflow-name: "MyExampleWorkflow"    # Required: Workflow Registry name
#   workflow-artifacts:
#     workflow-path: "./main.ts"            # Path to workflow entry point
#     config-path: "./config.yaml"          # Path to config file
#     secrets-path: "../secrets.yaml"       # Path to secrets file (project root by default)

# ==========================================================================
# Onchain Bond Issuance Workflow (HTTP Trigger from C#)
# ==========================================================================
staging-issuance:
  user-workflow:
    workflow-name: "onchain-workflow-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

production-issuance:
  user-workflow:
    workflow-name: "onchain-workflow-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""

# ==========================================================================
# ConvertibleBondCreated Event Listener Workflow
# Listens for ConvertibleBondCreated events and calls api/createBondConvert
# ==========================================================================
staging-bond-created-listener:
  user-workflow:
    workflow-name: "convertible-bond-listener-staging"
  workflow-artifacts:
    workflow-path: "./convertibleBondListener.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

production-bond-created-listener:
  user-workflow:
    workflow-name: "convertible-bond-listener-production"
  workflow-artifacts:
    workflow-path: "./convertibleBondListener.ts"
    config-path: "./config.production.json"
    secrets-path: ""
